<script setup lang="ts"></script>
<template>
    <ul class="integral-theory">
        <!-- <h4>What is the nature of reality?</h4> -->
        <h3>Ken Wilber's philosophical Integral framework has been the subject of his 
            best-selling, globally-translated books since the 1980s.</h3> 
        <p>He owns a number of public academic and consulting organizations 
            (unaffiliated.) In spite of an intense positive
            niche response, his "theory of everything" is nevertheless relatively obscure.</p>
        <img class="stu-banner" src="@/assets/img/kenwilber.jpg" />
        <h3>Integral theory exposes how people comprehend the nature of reality 
            and the experience of being.</h3> 
        <p> 
            Starting from the premise that every perspective is correct 
            at least through it's own set of lenses, the course was then to map out the definition and
            nature of lenses, and to organize and categorize the lenses that are known.
            One thing which becomes clear is that development is central to the nature of lenses.
            Historically, human nature has been to deny or suppress this observation in
            many ways. </p>
        <img class="stu-banner" style="filter: invert(1);" src="@/assets/img/kwquads.png" />
        <h3>A new tide is rising - a Second Tier, or Integral Stage, of human development.</h3> 
        <p>Integral thinkers (Teal and Turquoise Altitudes) view life and reality in terms of the holistic 
            evolution and inter-relatedness of complex systems. Civilization, nature, and the self can be
            can be said to be evolving at an increasing rate, towards greater complexity of perspective,
            and greater self-awareness (which is attractive.)</p>
        <h3>Worldview paradigms, or memes, act as lenses underlying our capacity to Think, Feel, and Do 👉🏿 Good, True, and Beautiful.</h3>
        <h2>Altitudes: 12 Stages of Consciousness</h2>
        <img class="stu-banner" src="@/assets/img/AltitudesModel.svg" />
        <h3>Transcend and Include</h3>

        <p>Higher is not better, or smarter. There's nothing more smart and lovable than a baby. You don't 
            plant a seed for it to wither and die. We embrace self and culture at all Levels. Authentic participants. 
            Our morality is to celebrate abundance and nurture the healthy development of all individuals, perhaps while 
            assisting with conflicts generated by turbulent First Tier interactions - that is to say, the world in which 
            we live. </p>
        <h3>We are intuitive, empathetic, open to all 
            perspectives and wisdom, universal-doner personalities, 
            actively engaged with genuine emotional vulnerability, detatched from identity 
            status and limiting beliefs. </h3>
        <h3>We are self-conscious, story-telling body pilots.</h3>
        <!-- <p>Right now in every moment you are consciousness. Of reality. They include one another. One and the same. It's not to reduce one to another, but to appreciate that reality has an internal and external dimension.</p> -->
        <h2><RouterLink to="/Integral">AQALALATAS Map:</RouterLink> I've constructed a model of Integral concepts in my own style.</h2>
        <h3>Visit <RouterLink to="/UnThinkMe">unThinkMe</RouterLink> for Integral tutorials and discussion.</h3>
    </ul>
</template>
