name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install app
      run: npm ci
    - name: run Vitest tests
      run: npm run test:unit
    - name: build app to production
      run: npm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: End to End test with Playwright
      run: npm run test:e2e
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@latest
      with:
        arg: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

    # - name: Deploy to firebase preview channel
    #   uses: FirebaseExtended/action-hosting-deploy@v0
    #   with:
    #     repoToken: "${{ secrets.GITHUB_TOKEN }}"
    #     firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_STEIN_UNLIMITED }}"
    #     projectId: stein-unlimited
    #     channelId: preview
        # channelId: production

